// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAICwL3CZ7sSmejQ9F4UQKHTp2YoQuGQUU',
    appId: '1:1081847148909:web:d8e4f0d985c47ffae86a64',
    messagingSenderId: '1081847148909',
    projectId: 'sport-compare',
    authDomain: 'sport-compare.firebaseapp.com',
    storageBucket: 'sport-compare.firebasestorage.app',
    measurementId: 'G-0EGY65BW0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnlVn1hg8ALduhMBhc2nnmkzXTheNFaA',
    appId: '1:1081847148909:android:076a3274ba895077e86a64',
    messagingSenderId: '1081847148909',
    projectId: 'sport-compare',
    storageBucket: 'sport-compare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNl_CBf1IJiSNpYR5-V709jRkre8h2dP0',
    appId: '1:1081847148909:ios:a5c28e3bd4d8e465e86a64',
    messagingSenderId: '1081847148909',
    projectId: 'sport-compare',
    storageBucket: 'sport-compare.firebasestorage.app',
    iosBundleId: 'com.example.tfgInformatica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNl_CBf1IJiSNpYR5-V709jRkre8h2dP0',
    appId: '1:1081847148909:ios:a5c28e3bd4d8e465e86a64',
    messagingSenderId: '1081847148909',
    projectId: 'sport-compare',
    storageBucket: 'sport-compare.firebasestorage.app',
    iosBundleId: 'com.example.tfgInformatica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAICwL3CZ7sSmejQ9F4UQKHTp2YoQuGQUU',
    appId: '1:1081847148909:web:877cb6b6195d9134e86a64',
    messagingSenderId: '1081847148909',
    projectId: 'sport-compare',
    authDomain: 'sport-compare.firebaseapp.com',
    storageBucket: 'sport-compare.firebasestorage.app',
    measurementId: 'G-FBSXH5J62P',
  );
}
